import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navber from "@/component/navber/Navber";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} bg-background text-white font-serif w-full `}>
        

      
        <Navber>
        {children}
        </Navber>
        
      </body>
    </html>
  );
}
